-- Generated by scripts/generate-seed.ts — do not edit by hand.
--
-- Demonstration data: every business, price, review and phone number here is
-- invented. It exists so the schema is exercised by realistic rows before any
-- real caterer is onboarded, and so a fresh project has something to render.
--
-- Re-runnable: every statement is an upsert.

begin;

-- Add-on services ----------------------------------------------------------
insert into add_on_services (id, name, category, unit, price_from, icon, scales_with_guests) values ('addon-cake', '{"en":"Celebration cake","fr":"Gâteau de fête"}'::localized, 'cake', '{"en":"per cake","fr":"par gâteau"}'::localized, 25000, '🎂', false)
on conflict (id) do update set name = excluded.name, unit = excluded.unit, price_from = excluded.price_from, icon = excluded.icon, scales_with_guests = excluded.scales_with_guests;
insert into add_on_services (id, name, category, unit, price_from, icon, scales_with_guests) values ('addon-drinks', '{"en":"Drinks & bar service","fr":"Boissons & bar"}'::localized, 'drinks', '{"en":"per guest","fr":"par invité"}'::localized, 1500, '🥤', true)
on conflict (id) do update set name = excluded.name, unit = excluded.unit, price_from = excluded.price_from, icon = excluded.icon, scales_with_guests = excluded.scales_with_guests;
insert into add_on_services (id, name, category, unit, price_from, icon, scales_with_guests) values ('addon-waitstaff', '{"en":"Waiters & hostesses","fr":"Serveurs & hôtesses"}'::localized, 'waitstaff', '{"en":"per person / day","fr":"par personne / jour"}'::localized, 12000, '🤵', true)
on conflict (id) do update set name = excluded.name, unit = excluded.unit, price_from = excluded.price_from, icon = excluded.icon, scales_with_guests = excluded.scales_with_guests;
insert into add_on_services (id, name, category, unit, price_from, icon, scales_with_guests) values ('addon-chairs', '{"en":"Chairs (Chiavari)","fr":"Chaises (Chiavari)"}'::localized, 'chairs', '{"en":"per chair","fr":"par chaise"}'::localized, 500, '🪑', true)
on conflict (id) do update set name = excluded.name, unit = excluded.unit, price_from = excluded.price_from, icon = excluded.icon, scales_with_guests = excluded.scales_with_guests;
insert into add_on_services (id, name, category, unit, price_from, icon, scales_with_guests) values ('addon-tables', '{"en":"Tables & linens","fr":"Tables & nappes"}'::localized, 'tables', '{"en":"per table","fr":"par table"}'::localized, 3000, '🍽️', true)
on conflict (id) do update set name = excluded.name, unit = excluded.unit, price_from = excluded.price_from, icon = excluded.icon, scales_with_guests = excluded.scales_with_guests;
insert into add_on_services (id, name, category, unit, price_from, icon, scales_with_guests) values ('addon-decor', '{"en":"Décor & flowers","fr":"Décoration & fleurs"}'::localized, 'decoration', '{"en":"per event","fr":"par événement"}'::localized, 75000, '🎈', false)
on conflict (id) do update set name = excluded.name, unit = excluded.unit, price_from = excluded.price_from, icon = excluded.icon, scales_with_guests = excluded.scales_with_guests;
insert into add_on_services (id, name, category, unit, price_from, icon, scales_with_guests) values ('addon-rentals', '{"en":"Canopies & rentals","fr":"Bâches & location"}'::localized, 'rentals', '{"en":"per unit","fr":"par unité"}'::localized, 20000, '⛺', false)
on conflict (id) do update set name = excluded.name, unit = excluded.unit, price_from = excluded.price_from, icon = excluded.icon, scales_with_guests = excluded.scales_with_guests;

-- Caterers -----------------------------------------------------------------
insert into caterers (id, business_name, tagline, about, city, service_areas, cuisines,
                      verification_status, featured, subscription_tier, rating, review_count,
                      completed_events, min_guests, price_from_per_guest, price_to_per_guest,
                      response_time_hours, years_active, phone, whatsapp, brand_hue, gallery)
values ('mamie-nkeng', 'Mamie Nkeng Traiteur', '{"en":"Authentic Cameroonian feasts for weddings & funerals","fr":"Festins camerounais authentiques pour mariages & funérailles"}'::localized, '{"en":"For over 12 years, Mamie Nkeng has cooked for the biggest weddings and traditional ceremonies in Douala. We are famous for Ndolé, Poulet DG and Eru made the way grandma taught. Every dish is prepared fresh on the morning of your event.","fr":"Depuis plus de 12 ans, Mamie Nkeng cuisine pour les plus grands mariages et cérémonies traditionnelles de Douala. Nous sommes réputés pour le Ndolé, le Poulet DG et l''Eru préparés comme grand-mère. Chaque plat est préparé frais le matin de votre événement."}'::localized,
        'Douala', ARRAY['Douala', 'Bonabéri', 'Edéa']::text[], ARRAY['cameroonian', 'grill', 'continental']::cuisine[],
        'approved', true, 'premium',
        4.9, 128, 340, 20,
        3500, 9000, 2,
        12, '+237699123456', '237699123456',
        145, ARRAY['Wedding buffet', 'Traditional plates', 'Grilled fish table', 'Ndolé pot']::text[])
on conflict (id) do update set business_name = excluded.business_name,
  tagline = excluded.tagline, about = excluded.about, city = excluded.city,
  service_areas = excluded.service_areas, cuisines = excluded.cuisines,
  min_guests = excluded.min_guests, price_from_per_guest = excluded.price_from_per_guest,
  price_to_per_guest = excluded.price_to_per_guest, gallery = excluded.gallery;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('mamie-nkeng--pkg-20', 'mamie-nkeng', '{"en":"Intimate — 20 guests","fr":"Intime — 20 invités"}'::localized, 20,
        5200, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Delivery & setup","fr":"Livraison & installation"}]'::jsonb, false)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('mamie-nkeng--pkg-50', 'mamie-nkeng', '{"en":"Family — 50 guests","fr":"Famille — 50 invités"}'::localized, 50,
        4500, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Waitstaff included","fr":"Service inclus"}]'::jsonb, true)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('mamie-nkeng--pkg-100', 'mamie-nkeng', '{"en":"Celebration — 100 guests","fr":"Célébration — 100 invités"}'::localized, 100,
        4150, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Waitstaff included","fr":"Service inclus"}]'::jsonb, true)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('mamie-nkeng--pkg-200', 'mamie-nkeng', '{"en":"Grand event — 200 guests","fr":"Grand événement — 200 invités"}'::localized, 200,
        3850, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Waitstaff included","fr":"Service inclus"}]'::jsonb, true)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('mamie-nkeng--ndole-0', 'mamie-nkeng', 'Ndolé & Prawns', '{"en":"Bitterleaf stew with prawns and beef, served with fried plantain","fr":"Bitterleaf stew with prawns and beef, served with fried plantain"}'::localized,
        'cameroonian', 3500)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('mamie-nkeng--dg-1', 'mamie-nkeng', 'Poulet DG', '{"en":"Sautéed chicken with plantains, carrots and green beans","fr":"Sautéed chicken with plantains, carrots and green beans"}'::localized,
        'cameroonian', 3000)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('mamie-nkeng--eru-2', 'mamie-nkeng', 'Eru & Water Fufu', '{"en":"Forest leaves with waterleaf, cow skin and smoked fish","fr":"Forest leaves with waterleaf, cow skin and smoked fish"}'::localized,
        'cameroonian', 2500)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('mamie-nkeng--jollof-3', 'mamie-nkeng', 'Jollof Rice & Grilled Chicken', '{"en":"Party jollof with barbecue chicken","fr":"Party jollof with barbecue chicken"}'::localized,
        'grill', 2800)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('mamie-nkeng--fish-4', 'mamie-nkeng', 'Grilled Bar Fish', '{"en":"Whole grilled fish with pepper sauce and miondo","fr":"Whole grilled fish with pepper sauce and miondo"}'::localized,
        'seafood', 4000)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into caterer_blocked_dates (caterer_id, date, reason)
values ('mamie-nkeng', '2026-07-18', 'seed data')
on conflict (caterer_id, date) do nothing;
insert into caterer_blocked_dates (caterer_id, date, reason)
values ('mamie-nkeng', '2026-07-25', 'seed data')
on conflict (caterer_id, date) do nothing;
insert into caterer_blocked_dates (caterer_id, date, reason)
values ('mamie-nkeng', '2026-08-01', 'seed data')
on conflict (caterer_id, date) do nothing;
insert into caterer_blocked_dates (caterer_id, date, reason)
values ('mamie-nkeng', '2026-08-15', 'seed data')
on conflict (caterer_id, date) do nothing;

insert into caterers (id, business_name, tagline, about, city, service_areas, cuisines,
                      verification_status, featured, subscription_tier, rating, review_count,
                      completed_events, min_guests, price_from_per_guest, price_to_per_guest,
                      response_time_hours, years_active, phone, whatsapp, brand_hue, gallery)
values ('royal-taste', 'Royal Taste Events', '{"en":"Professional catering & full event service in Yaoundé","fr":"Traiteur professionnel & service complet à Yaoundé"}'::localized, '{"en":"Royal Taste is a full-service catering company trusted by embassies, ministries and corporate clients. We combine Cameroonian classics with continental fine dining, and can handle events from 20 to 1,000 guests with uniformed waitstaff.","fr":"Royal Taste est une entreprise de traiteur complète, choisie par les ambassades, ministères et entreprises. Nous associons classiques camerounais et cuisine continentale, pour des événements de 20 à 1 000 invités avec personnel en uniforme."}'::localized,
        'Yaoundé', ARRAY['Yaoundé', 'Mbalmayo', 'Obala']::text[], ARRAY['continental', 'cameroonian', 'asian', 'pastry']::cuisine[],
        'approved', true, 'premium',
        4.8, 96, 210, 20,
        5000, 15000, 3,
        8, '+237677889900', '237677889900',
        205, ARRAY['Corporate gala', 'Buffet line', 'Canapé trays', 'Head table']::text[])
on conflict (id) do update set business_name = excluded.business_name,
  tagline = excluded.tagline, about = excluded.about, city = excluded.city,
  service_areas = excluded.service_areas, cuisines = excluded.cuisines,
  min_guests = excluded.min_guests, price_from_per_guest = excluded.price_from_per_guest,
  price_to_per_guest = excluded.price_to_per_guest, gallery = excluded.gallery;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('royal-taste--pkg-20', 'royal-taste', '{"en":"Intimate — 20 guests","fr":"Intime — 20 invités"}'::localized, 20,
        7450, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Delivery & setup","fr":"Livraison & installation"}]'::jsonb, false)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('royal-taste--pkg-50', 'royal-taste', '{"en":"Family — 50 guests","fr":"Famille — 50 invités"}'::localized, 50,
        6500, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Waitstaff included","fr":"Service inclus"}]'::jsonb, true)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('royal-taste--pkg-100', 'royal-taste', '{"en":"Celebration — 100 guests","fr":"Célébration — 100 invités"}'::localized, 100,
        6000, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Waitstaff included","fr":"Service inclus"}]'::jsonb, true)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('royal-taste--pkg-200', 'royal-taste', '{"en":"Grand event — 200 guests","fr":"Grand événement — 200 invités"}'::localized, 200,
        5550, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Waitstaff included","fr":"Service inclus"}]'::jsonb, true)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('royal-taste--buffet-0', 'royal-taste', 'Continental Buffet', '{"en":"Roast beef, grilled fish, rice pilaf, ratatouille and salads","fr":"Roast beef, grilled fish, rice pilaf, ratatouille and salads"}'::localized,
        'continental', 6000)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('royal-taste--canape-1', 'royal-taste', 'Cocktail Canapés', '{"en":"Assorted finger food for standing receptions","fr":"Assorted finger food for standing receptions"}'::localized,
        'continental', 4500)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('royal-taste--dg-2', 'royal-taste', 'Poulet DG Deluxe', '{"en":"Premium Poulet DG with gizzards and plantain","fr":"Premium Poulet DG with gizzards and plantain"}'::localized,
        'cameroonian', 3500)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('royal-taste--fried-3', 'royal-taste', 'Fried Rice & Chicken', '{"en":"Asian-style fried rice with glazed chicken","fr":"Asian-style fried rice with glazed chicken"}'::localized,
        'asian', 3200)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('royal-taste--dessert-4', 'royal-taste', 'Dessert Station', '{"en":"Pastries, fruit and mini cakes","fr":"Pastries, fruit and mini cakes"}'::localized,
        'pastry', 2500)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into caterer_blocked_dates (caterer_id, date, reason)
values ('royal-taste', '2026-07-12', 'seed data')
on conflict (caterer_id, date) do nothing;
insert into caterer_blocked_dates (caterer_id, date, reason)
values ('royal-taste', '2026-07-19', 'seed data')
on conflict (caterer_id, date) do nothing;
insert into caterer_blocked_dates (caterer_id, date, reason)
values ('royal-taste', '2026-08-08', 'seed data')
on conflict (caterer_id, date) do nothing;
insert into caterer_blocked_dates (caterer_id, date, reason)
values ('royal-taste', '2026-08-22', 'seed data')
on conflict (caterer_id, date) do nothing;
insert into caterer_blocked_dates (caterer_id, date, reason)
values ('royal-taste', '2026-09-05', 'seed data')
on conflict (caterer_id, date) do nothing;

insert into caterers (id, business_name, tagline, about, city, service_areas, cuisines,
                      verification_status, featured, subscription_tier, rating, review_count,
                      completed_events, min_guests, price_from_per_guest, price_to_per_guest,
                      response_time_hours, years_active, phone, whatsapp, brand_hue, gallery)
values ('bamenda-flavors', 'Bamenda Flavors Kitchen', '{"en":"Home-style Grassfield cooking for family gatherings","fr":"Cuisine du Grassfield pour les fêtes de famille"}'::localized, '{"en":"A home-based caterer specialising in North-West favourites — Achu and yellow soup, Corn Fufu and Njama Njama, Kati Kati chicken. Affordable, generous portions and a warm personal touch for weddings, cry-die and thanksgivings.","fr":"Traiteur à domicile spécialisé dans les plats du Nord-Ouest — Achu et sauce jaune, Corn Fufu et Njama Njama, poulet Kati Kati. Portions généreuses et abordables pour mariages, deuils et actions de grâce."}'::localized,
        'Bamenda', ARRAY['Bamenda', 'Bafut', 'Bali']::text[], ARRAY['cameroonian', 'grill']::cuisine[],
        'approved', false, 'free',
        4.7, 54, 130, 20,
        2500, 6000, 5,
        6, '+237671223344', '237671223344',
        25, ARRAY['Achu bowls', 'Family buffet', 'Kati Kati grill', 'Village setup']::text[])
on conflict (id) do update set business_name = excluded.business_name,
  tagline = excluded.tagline, about = excluded.about, city = excluded.city,
  service_areas = excluded.service_areas, cuisines = excluded.cuisines,
  min_guests = excluded.min_guests, price_from_per_guest = excluded.price_from_per_guest,
  price_to_per_guest = excluded.price_to_per_guest, gallery = excluded.gallery;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('bamenda-flavors--pkg-20', 'bamenda-flavors', '{"en":"Intimate — 20 guests","fr":"Intime — 20 invités"}'::localized, 20,
        3450, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Delivery & setup","fr":"Livraison & installation"}]'::jsonb, false)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('bamenda-flavors--pkg-50', 'bamenda-flavors', '{"en":"Family — 50 guests","fr":"Famille — 50 invités"}'::localized, 50,
        3000, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Delivery & setup","fr":"Livraison & installation"}]'::jsonb, false)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('bamenda-flavors--pkg-100', 'bamenda-flavors', '{"en":"Celebration — 100 guests","fr":"Célébration — 100 invités"}'::localized, 100,
        2750, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Waitstaff included","fr":"Service inclus"}]'::jsonb, true)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('bamenda-flavors--pkg-200', 'bamenda-flavors', '{"en":"Grand event — 200 guests","fr":"Grand événement — 200 invités"}'::localized, 200,
        2550, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Waitstaff included","fr":"Service inclus"}]'::jsonb, true)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('bamenda-flavors--achu-0', 'bamenda-flavors', 'Achu & Yellow Soup', '{"en":"Pounded cocoyam with limestone yellow soup and beef","fr":"Pounded cocoyam with limestone yellow soup and beef"}'::localized,
        'cameroonian', 3000)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('bamenda-flavors--njama-1', 'bamenda-flavors', 'Corn Fufu & Njama Njama', '{"en":"Huckleberry greens with corn fufu","fr":"Huckleberry greens with corn fufu"}'::localized,
        'cameroonian', 2200)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('bamenda-flavors--katikati-2', 'bamenda-flavors', 'Kati Kati Chicken', '{"en":"Roasted chicken in palm oil with achu spices","fr":"Roasted chicken in palm oil with achu spices"}'::localized,
        'grill', 3200)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('bamenda-flavors--rice-3', 'bamenda-flavors', 'Coconut Rice', '{"en":"Rice cooked in coconut milk with vegetables","fr":"Rice cooked in coconut milk with vegetables"}'::localized,
        'cameroonian', 2000)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into caterer_blocked_dates (caterer_id, date, reason)
values ('bamenda-flavors', '2026-07-26', 'seed data')
on conflict (caterer_id, date) do nothing;
insert into caterer_blocked_dates (caterer_id, date, reason)
values ('bamenda-flavors', '2026-08-09', 'seed data')
on conflict (caterer_id, date) do nothing;

insert into caterers (id, business_name, tagline, about, city, service_areas, cuisines,
                      verification_status, featured, subscription_tier, rating, review_count,
                      completed_events, min_guests, price_from_per_guest, price_to_per_guest,
                      response_time_hours, years_active, phone, whatsapp, brand_hue, gallery)
values ('buea-delights', 'Buea Mountain Delights', '{"en":"Fresh seafood & continental menus at the foot of the mountain","fr":"Fruits de mer frais & menus continentaux au pied du mont"}'::localized, '{"en":"Based in Buea, we bring fresh Limbe seafood to your table — grilled prawns, bar fish, and pepper soup — alongside continental options for a modern crowd. Popular for beach weddings, birthdays and university events.","fr":"Basés à Buea, nous apportons les fruits de mer frais de Limbe — crevettes grillées, poisson bar et pepper soup — avec des options continentales pour un public moderne. Idéal pour mariages sur la plage, anniversaires et événements universitaires."}'::localized,
        'Buea', ARRAY['Buea', 'Limbe', 'Tiko', 'Mutengene']::text[], ARRAY['seafood', 'continental', 'grill']::cuisine[],
        'approved', true, 'free',
        4.6, 71, 95, 20,
        4000, 11000, 4,
        5, '+237655443322', '237655443322',
        190, ARRAY['Seafood platter', 'Beach setup', 'Pepper soup pots', 'Grill station']::text[])
on conflict (id) do update set business_name = excluded.business_name,
  tagline = excluded.tagline, about = excluded.about, city = excluded.city,
  service_areas = excluded.service_areas, cuisines = excluded.cuisines,
  min_guests = excluded.min_guests, price_from_per_guest = excluded.price_from_per_guest,
  price_to_per_guest = excluded.price_to_per_guest, gallery = excluded.gallery;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('buea-delights--pkg-20', 'buea-delights', '{"en":"Intimate — 20 guests","fr":"Intime — 20 invités"}'::localized, 20,
        5750, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Delivery & setup","fr":"Livraison & installation"}]'::jsonb, false)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('buea-delights--pkg-50', 'buea-delights', '{"en":"Family — 50 guests","fr":"Famille — 50 invités"}'::localized, 50,
        5000, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Waitstaff included","fr":"Service inclus"}]'::jsonb, true)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('buea-delights--pkg-100', 'buea-delights', '{"en":"Celebration — 100 guests","fr":"Célébration — 100 invités"}'::localized, 100,
        4600, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Waitstaff included","fr":"Service inclus"}]'::jsonb, true)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('buea-delights--pkg-200', 'buea-delights', '{"en":"Grand event — 200 guests","fr":"Grand événement — 200 invités"}'::localized, 200,
        4250, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Waitstaff included","fr":"Service inclus"}]'::jsonb, true)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('buea-delights--prawns-0', 'buea-delights', 'Grilled Prawn Platter', '{"en":"Fresh Limbe prawns grilled with garlic butter","fr":"Fresh Limbe prawns grilled with garlic butter"}'::localized,
        'seafood', 5500)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('buea-delights--peppersoup-1', 'buea-delights', 'Fish Pepper Soup', '{"en":"Spicy catfish pepper soup with country onions","fr":"Spicy catfish pepper soup with country onions"}'::localized,
        'seafood', 3000)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('buea-delights--burger-2', 'buea-delights', 'Continental Grill', '{"en":"Beef steak, sausages and grilled vegetables","fr":"Beef steak, sausages and grilled vegetables"}'::localized,
        'grill', 4500)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('buea-delights--salad-3', 'buea-delights', 'Garden Salad Bar', '{"en":"Fresh salad station with dressings","fr":"Fresh salad station with dressings"}'::localized,
        'continental', 2000)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into caterer_blocked_dates (caterer_id, date, reason)
values ('buea-delights', '2026-07-15', 'seed data')
on conflict (caterer_id, date) do nothing;
insert into caterer_blocked_dates (caterer_id, date, reason)
values ('buea-delights', '2026-07-30', 'seed data')
on conflict (caterer_id, date) do nothing;
insert into caterer_blocked_dates (caterer_id, date, reason)
values ('buea-delights', '2026-08-14', 'seed data')
on conflict (caterer_id, date) do nothing;

insert into caterers (id, business_name, tagline, about, city, service_areas, cuisines,
                      verification_status, featured, subscription_tier, rating, review_count,
                      completed_events, min_guests, price_from_per_guest, price_to_per_guest,
                      response_time_hours, years_active, phone, whatsapp, brand_hue, gallery)
values ('sweet-celebration', 'Sweet Celebration Bakery', '{"en":"Cakes, pastries & dessert tables that steal the show","fr":"Gâteaux, pâtisseries & tables de dessert qui font sensation"}'::localized, '{"en":"A boutique bakery for weddings, birthdays and corporate events. We design custom cakes, cupcake towers and full dessert tables. Pair us with any caterer on the platform, or book us for a sweet-only event.","fr":"Une pâtisserie boutique pour mariages, anniversaires et événements d''entreprise. Nous créons gâteaux sur mesure, tours de cupcakes et tables de dessert complètes. Associez-nous à tout traiteur, ou réservez-nous seuls."}'::localized,
        'Douala', ARRAY['Douala', 'Yaoundé (on request)']::text[], ARRAY['pastry']::cuisine[],
        'approved', false, 'premium',
        4.9, 143, 400, 20,
        1500, 5000, 6,
        7, '+237690102030', '237690102030',
        330, ARRAY['Wedding cake', 'Cupcake tower', 'Dessert table', 'Macaron trays']::text[])
on conflict (id) do update set business_name = excluded.business_name,
  tagline = excluded.tagline, about = excluded.about, city = excluded.city,
  service_areas = excluded.service_areas, cuisines = excluded.cuisines,
  min_guests = excluded.min_guests, price_from_per_guest = excluded.price_from_per_guest,
  price_to_per_guest = excluded.price_to_per_guest, gallery = excluded.gallery;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('sweet-celebration--pkg-20', 'sweet-celebration', '{"en":"Intimate — 20 guests","fr":"Intime — 20 invités"}'::localized, 20,
        2300, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Delivery & setup","fr":"Livraison & installation"}]'::jsonb, false)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('sweet-celebration--pkg-50', 'sweet-celebration', '{"en":"Family — 50 guests","fr":"Famille — 50 invités"}'::localized, 50,
        2000, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Delivery & setup","fr":"Livraison & installation"}]'::jsonb, false)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('sweet-celebration--pkg-100', 'sweet-celebration', '{"en":"Celebration — 100 guests","fr":"Célébration — 100 invités"}'::localized, 100,
        1850, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Delivery & setup","fr":"Livraison & installation"}]'::jsonb, false)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('sweet-celebration--pkg-200', 'sweet-celebration', '{"en":"Grand event — 200 guests","fr":"Grand événement — 200 invités"}'::localized, 200,
        1700, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Delivery & setup","fr":"Livraison & installation"}]'::jsonb, false)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('sweet-celebration--cake-0', 'sweet-celebration', 'Custom Tiered Cake', '{"en":"3-tier celebration cake, your design","fr":"3-tier celebration cake, your design"}'::localized,
        'pastry', 3000)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('sweet-celebration--cupcakes-1', 'sweet-celebration', 'Cupcake Tower', '{"en":"Assorted gourmet cupcakes","fr":"Assorted gourmet cupcakes"}'::localized,
        'pastry', 1200)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('sweet-celebration--table-2', 'sweet-celebration', 'Dessert Table', '{"en":"Cake pops, macarons, tarts and mini pastries","fr":"Cake pops, macarons, tarts and mini pastries"}'::localized,
        'pastry', 2500)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('sweet-celebration--puff-3', 'sweet-celebration', 'Puff-Puff & Chin Chin', '{"en":"Classic Cameroonian party snacks","fr":"Classic Cameroonian party snacks"}'::localized,
        'pastry', 800)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into caterer_blocked_dates (caterer_id, date, reason)
values ('sweet-celebration', '2026-07-20', 'seed data')
on conflict (caterer_id, date) do nothing;

insert into caterers (id, business_name, tagline, about, city, service_areas, cuisines,
                      verification_status, featured, subscription_tier, rating, review_count,
                      completed_events, min_guests, price_from_per_guest, price_to_per_guest,
                      response_time_hours, years_active, phone, whatsapp, brand_hue, gallery)
values ('bafoussam-royal', 'Bafoussam Royal Kitchen', '{"en":"Big Bamileke ceremonies handled with pride","fr":"Grandes cérémonies Bamiléké gérées avec fierté"}'::localized, '{"en":"We specialise in large West-region ceremonies — funerals, dowries and successions — where hundreds must be fed with dignity. Rice, koki, taro and grilled meats in industrial quantities, delivered on time, every time.","fr":"Nous sommes spécialisés dans les grandes cérémonies de l''Ouest — funérailles, dots et successions — où des centaines de personnes doivent être servies avec dignité. Riz, koki, taro et grillades en grande quantité, livrés à temps."}'::localized,
        'Bafoussam', ARRAY['Bafoussam', 'Dschang', 'Mbouda', 'Bandjoun']::text[], ARRAY['cameroonian', 'grill']::cuisine[],
        'approved', false, 'free',
        4.5, 38, 160, 50,
        2000, 5500, 8,
        10, '+237696556677', '237696556677',
        45, ARRAY['Ceremony tent', 'Rice service', 'Grill line', 'Koki leaves']::text[])
on conflict (id) do update set business_name = excluded.business_name,
  tagline = excluded.tagline, about = excluded.about, city = excluded.city,
  service_areas = excluded.service_areas, cuisines = excluded.cuisines,
  min_guests = excluded.min_guests, price_from_per_guest = excluded.price_from_per_guest,
  price_to_per_guest = excluded.price_to_per_guest, gallery = excluded.gallery;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('bafoussam-royal--pkg-20', 'bafoussam-royal', '{"en":"Intimate — 20 guests","fr":"Intime — 20 invités"}'::localized, 20,
        3000, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Delivery & setup","fr":"Livraison & installation"}]'::jsonb, false)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('bafoussam-royal--pkg-50', 'bafoussam-royal', '{"en":"Family — 50 guests","fr":"Famille — 50 invités"}'::localized, 50,
        2600, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Delivery & setup","fr":"Livraison & installation"}]'::jsonb, false)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('bafoussam-royal--pkg-100', 'bafoussam-royal', '{"en":"Celebration — 100 guests","fr":"Célébration — 100 invités"}'::localized, 100,
        2400, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Waitstaff included","fr":"Service inclus"}]'::jsonb, true)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('bafoussam-royal--pkg-200', 'bafoussam-royal', '{"en":"Grand event — 200 guests","fr":"Grand événement — 200 invités"}'::localized, 200,
        2200, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Waitstaff included","fr":"Service inclus"}]'::jsonb, true)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('bafoussam-royal--koki-0', 'bafoussam-royal', 'Koki & Ripe Plantain', '{"en":"Steamed black-eyed pea pudding with plantain","fr":"Steamed black-eyed pea pudding with plantain"}'::localized,
        'cameroonian', 2000)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('bafoussam-royal--taro-1', 'bafoussam-royal', 'Taro & Yellow Soup', '{"en":"Taro with palm-oil yellow soup","fr":"Taro with palm-oil yellow soup"}'::localized,
        'cameroonian', 2400)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('bafoussam-royal--rice-2', 'bafoussam-royal', 'Party Rice & Beef', '{"en":"Seasoned rice with stewed beef","fr":"Seasoned rice with stewed beef"}'::localized,
        'cameroonian', 1800)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('bafoussam-royal--soya-3', 'bafoussam-royal', 'Soya Grill', '{"en":"Spiced grilled beef skewers","fr":"Spiced grilled beef skewers"}'::localized,
        'grill', 2200)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into caterer_blocked_dates (caterer_id, date, reason)
values ('bafoussam-royal', '2026-07-11', 'seed data')
on conflict (caterer_id, date) do nothing;
insert into caterer_blocked_dates (caterer_id, date, reason)
values ('bafoussam-royal', '2026-07-24', 'seed data')
on conflict (caterer_id, date) do nothing;
insert into caterer_blocked_dates (caterer_id, date, reason)
values ('bafoussam-royal', '2026-08-07', 'seed data')
on conflict (caterer_id, date) do nothing;
insert into caterer_blocked_dates (caterer_id, date, reason)
values ('bafoussam-royal', '2026-08-21', 'seed data')
on conflict (caterer_id, date) do nothing;

insert into caterers (id, business_name, tagline, about, city, service_areas, cuisines,
                      verification_status, featured, subscription_tier, rating, review_count,
                      completed_events, min_guests, price_from_per_guest, price_to_per_guest,
                      response_time_hours, years_active, phone, whatsapp, brand_hue, gallery)
values ('green-plate', 'Green Plate Healthy Catering', '{"en":"Vegetarian, vegan & healthy office lunches","fr":"Déjeuners de bureau végétariens, végans & sains"}'::localized, '{"en":"Modern, health-conscious catering for offices, NGOs and private dinners. Colourful vegetarian bowls, plant-based proteins and fresh cold-pressed juices. We make healthy eating easy for busy teams in Yaoundé and Douala.","fr":"Traiteur moderne et sain pour bureaux, ONG et dîners privés. Bols végétariens colorés, protéines végétales et jus pressés à froid. Nous facilitons l''alimentation saine des équipes à Yaoundé et Douala."}'::localized,
        'Yaoundé', ARRAY['Yaoundé', 'Douala']::text[], ARRAY['vegetarian', 'continental']::cuisine[],
        'pending', false, 'free',
        4.4, 22, 40, 20,
        3000, 7000, 4,
        2, '+237680405060', '237680405060',
        95, ARRAY['Grain bowls', 'Salad bar', 'Juice station', 'Office lunch']::text[])
on conflict (id) do update set business_name = excluded.business_name,
  tagline = excluded.tagline, about = excluded.about, city = excluded.city,
  service_areas = excluded.service_areas, cuisines = excluded.cuisines,
  min_guests = excluded.min_guests, price_from_per_guest = excluded.price_from_per_guest,
  price_to_per_guest = excluded.price_to_per_guest, gallery = excluded.gallery;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('green-plate--pkg-20', 'green-plate', '{"en":"Intimate — 20 guests","fr":"Intime — 20 invités"}'::localized, 20,
        4350, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Delivery & setup","fr":"Livraison & installation"}]'::jsonb, false)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('green-plate--pkg-50', 'green-plate', '{"en":"Family — 50 guests","fr":"Famille — 50 invités"}'::localized, 50,
        3800, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Delivery & setup","fr":"Livraison & installation"}]'::jsonb, false)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('green-plate--pkg-100', 'green-plate', '{"en":"Celebration — 100 guests","fr":"Célébration — 100 invités"}'::localized, 100,
        3500, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Waitstaff included","fr":"Service inclus"}]'::jsonb, true)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('green-plate--pkg-200', 'green-plate', '{"en":"Grand event — 200 guests","fr":"Grand événement — 200 invités"}'::localized, 200,
        3250, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Waitstaff included","fr":"Service inclus"}]'::jsonb, true)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('green-plate--bowl-0', 'green-plate', 'Power Grain Bowl', '{"en":"Quinoa, beans, avocado and roasted vegetables","fr":"Quinoa, beans, avocado and roasted vegetables"}'::localized,
        'vegetarian', 3500)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('green-plate--wrap-1', 'green-plate', 'Veggie Wraps', '{"en":"Whole-wheat wraps with hummus and greens","fr":"Whole-wheat wraps with hummus and greens"}'::localized,
        'vegetarian', 2500)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('green-plate--salad-2', 'green-plate', 'Rainbow Salad Bar', '{"en":"Build-your-own salad with 12 toppings","fr":"Build-your-own salad with 12 toppings"}'::localized,
        'vegetarian', 3000)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('green-plate--juice-3', 'green-plate', 'Cold-Pressed Juice', '{"en":"Ginger, pineapple and beetroot juices","fr":"Ginger, pineapple and beetroot juices"}'::localized,
        'continental', 1500)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;

insert into caterers (id, business_name, tagline, about, city, service_areas, cuisines,
                      verification_status, featured, subscription_tier, rating, review_count,
                      completed_events, min_guests, price_from_per_guest, price_to_per_guest,
                      response_time_hours, years_active, phone, whatsapp, brand_hue, gallery)
values ('kribi-coast', 'Kribi Coast Catering', '{"en":"Beachside seafood & grills for coastal celebrations","fr":"Fruits de mer & grillades en bord de mer pour vos fêtes"}'::localized, '{"en":"Kribi''s favourite for destination weddings and seaside parties. We serve just-caught seafood, gambas, and beach barbecue with a sunset view. Full setup with canopies, tables and waitstaff available.","fr":"Le favori de Kribi pour mariages et fêtes en bord de mer. Nous servons des fruits de mer fraîchement pêchés, gambas et barbecue de plage au coucher du soleil. Installation complète avec bâches, tables et service."}'::localized,
        'Kribi', ARRAY['Kribi', 'Edéa', 'Campo']::text[], ARRAY['seafood', 'grill', 'continental']::cuisine[],
        'approved', false, 'free',
        4.7, 33, 60, 20,
        4500, 12000, 6,
        4, '+237678129034', '237678129034',
        175, ARRAY['Beach wedding', 'Gambas grill', 'Sunset tables', 'Seafood spread']::text[])
on conflict (id) do update set business_name = excluded.business_name,
  tagline = excluded.tagline, about = excluded.about, city = excluded.city,
  service_areas = excluded.service_areas, cuisines = excluded.cuisines,
  min_guests = excluded.min_guests, price_from_per_guest = excluded.price_from_per_guest,
  price_to_per_guest = excluded.price_to_per_guest, gallery = excluded.gallery;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('kribi-coast--pkg-20', 'kribi-coast', '{"en":"Intimate — 20 guests","fr":"Intime — 20 invités"}'::localized, 20,
        6300, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Delivery & setup","fr":"Livraison & installation"}]'::jsonb, false)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('kribi-coast--pkg-50', 'kribi-coast', '{"en":"Family — 50 guests","fr":"Famille — 50 invités"}'::localized, 50,
        5500, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Waitstaff included","fr":"Service inclus"}]'::jsonb, true)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('kribi-coast--pkg-100', 'kribi-coast', '{"en":"Celebration — 100 guests","fr":"Célébration — 100 invités"}'::localized, 100,
        5050, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Waitstaff included","fr":"Service inclus"}]'::jsonb, true)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)
values ('kribi-coast--pkg-200', 'kribi-coast', '{"en":"Grand event — 200 guests","fr":"Grand événement — 200 invités"}'::localized, 200,
        4700, '[{"en":"2 main dishes + 2 sides","fr":"2 plats + 2 accompagnements"},{"en":"Starters & fresh juice","fr":"Entrées & jus frais"},{"en":"Waitstaff included","fr":"Service inclus"}]'::jsonb, true)
on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,
  highlights = excluded.highlights, includes_service = excluded.includes_service;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('kribi-coast--gambas-0', 'kribi-coast', 'Grilled Gambas', '{"en":"Giant prawns grilled with herbs and lime","fr":"Giant prawns grilled with herbs and lime"}'::localized,
        'seafood', 6000)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('kribi-coast--lobster-1', 'kribi-coast', 'Lobster & Plantain', '{"en":"Grilled lobster with fried plantain","fr":"Grilled lobster with fried plantain"}'::localized,
        'seafood', 8000)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('kribi-coast--bbq-2', 'kribi-coast', 'Beach BBQ Platter', '{"en":"Mixed grill of fish, chicken and beef","fr":"Mixed grill of fish, chicken and beef"}'::localized,
        'grill', 4500)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)
values ('kribi-coast--rice-3', 'kribi-coast', 'Coconut Seafood Rice', '{"en":"Coconut rice with prawns and calamari","fr":"Coconut rice with prawns and calamari"}'::localized,
        'seafood', 4000)
on conflict (id) do update set name = excluded.name, description = excluded.description,
  price_per_guest = excluded.price_per_guest;
insert into caterer_blocked_dates (caterer_id, date, reason)
values ('kribi-coast', '2026-08-02', 'seed data')
on conflict (caterer_id, date) do nothing;
insert into caterer_blocked_dates (caterer_id, date, reason)
values ('kribi-coast', '2026-08-16', 'seed data')
on conflict (caterer_id, date) do nothing;

commit;
