/**
 * Generate supabase/seed.sql from the seed data in src/data.
 *
 * The seed data is the only description of this marketplace that exists, so it
 * is also the only thing that can exercise the schema before real caterers do.
 * Generating the SQL rather than hand-writing it keeps the two in step: change
 * a caterer in src/data and the seed follows.
 *
 *   npm run db:seed:generate
 *
 * The output is safe to re-run — every insert is an upsert keyed on the primary
 * key, so applying it twice does not duplicate a marketplace.
 */
import { writeFileSync } from "node:fs";
import { caterers } from "../src/data/caterers";
import { addOns } from "../src/data/addons";

const q = (v: string) => `'${v.replace(/'/g, "''")}'`;
const localized = (v: { en: string; fr: string }) =>
  `${q(JSON.stringify({ en: v.en, fr: v.fr }))}::localized`;
const arr = (v: readonly string[]) =>
  `ARRAY[${v.map(q).join(", ")}]::text[]`;
const enumArr = (v: readonly string[], type: string) =>
  `ARRAY[${v.map(q).join(", ")}]::${type}[]`;

const lines: string[] = [
  "-- Generated by scripts/generate-seed.ts — do not edit by hand.",
  "--",
  "-- Demonstration data: every business, price, review and phone number here is",
  "-- invented. It exists so the schema is exercised by realistic rows before any",
  "-- real caterer is onboarded, and so a fresh project has something to render.",
  "--",
  "-- Re-runnable: every statement is an upsert.",
  "",
  "begin;",
  "",
];

lines.push("-- Add-on services ----------------------------------------------------------");
const scaling = ["drinks", "waitstaff", "chairs", "tables"];
for (const a of addOns) {
  lines.push(
    `insert into add_on_services (id, name, category, unit, price_from, icon, scales_with_guests) values (` +
      `${q(a.id)}, ${localized(a.name)}, ${q(a.category)}, ${localized(a.unit)}, ` +
      `${a.priceFrom}, ${q(a.icon)}, ${scaling.includes(a.category)})` +
      `\non conflict (id) do update set name = excluded.name, unit = excluded.unit, ` +
      `price_from = excluded.price_from, icon = excluded.icon, ` +
      `scales_with_guests = excluded.scales_with_guests;`
  );
}
lines.push("");

lines.push("-- Caterers -----------------------------------------------------------------");
for (const c of caterers) {
  lines.push(
    `insert into caterers (id, business_name, tagline, about, city, service_areas, cuisines,\n` +
      `                      verification_status, featured, subscription_tier, rating, review_count,\n` +
      `                      completed_events, min_guests, price_from_per_guest, price_to_per_guest,\n` +
      `                      response_time_hours, years_active, phone, whatsapp, brand_hue, gallery)\n` +
      `values (${q(c.id)}, ${q(c.businessName)}, ${localized(c.tagline)}, ${localized(c.about)},\n` +
      `        ${q(c.city)}, ${arr(c.serviceAreas)}, ${enumArr(c.cuisines, "cuisine")},\n` +
      `        ${q(c.verified ? "approved" : "pending")}, ${c.featured}, ${q(c.subscriptionTier)},\n` +
      `        ${c.rating}, ${c.reviewCount}, ${c.completedEvents}, ${c.minGuests},\n` +
      `        ${c.priceFromPerGuest}, ${c.priceToPerGuest}, ${c.responseTimeHours},\n` +
      `        ${c.yearsActive}, ${q(c.phone.replace(/\s/g, ""))}, ${q(c.whatsapp)},\n` +
      `        ${c.brandHue}, ${arr(c.gallery)})\n` +
      `on conflict (id) do update set business_name = excluded.business_name,\n` +
      `  tagline = excluded.tagline, about = excluded.about, city = excluded.city,\n` +
      `  service_areas = excluded.service_areas, cuisines = excluded.cuisines,\n` +
      `  min_guests = excluded.min_guests, price_from_per_guest = excluded.price_from_per_guest,\n` +
      `  price_to_per_guest = excluded.price_to_per_guest, gallery = excluded.gallery;`
  );

  for (const p of c.packages) {
    lines.push(
      `insert into event_packages (id, caterer_id, name, guest_count, price_per_guest, highlights, includes_service)\n` +
        `values (${q(`${c.id}--${p.id}`)}, ${q(c.id)}, ${localized(p.name)}, ${p.guestCount},\n` +
        `        ${p.pricePerGuest}, ${q(JSON.stringify(p.highlights))}::jsonb, ${p.includesService})\n` +
        `on conflict (id) do update set name = excluded.name, price_per_guest = excluded.price_per_guest,\n` +
        `  highlights = excluded.highlights, includes_service = excluded.includes_service;`
    );
  }

  for (const m of c.menu) {
    lines.push(
      `insert into menu_items (id, caterer_id, name, description, cuisine, price_per_guest)\n` +
        `values (${q(`${c.id}--${m.id}`)}, ${q(c.id)}, ${q(m.name)}, ${localized(m.description)},\n` +
        `        ${q(m.cuisine)}, ${m.pricePerGuest})\n` +
        `on conflict (id) do update set name = excluded.name, description = excluded.description,\n` +
        `  price_per_guest = excluded.price_per_guest;`
    );
  }

  for (const d of c.bookedDates) {
    lines.push(
      `insert into caterer_blocked_dates (caterer_id, date, reason)\n` +
        `values (${q(c.id)}, ${q(d)}, 'seed data')\n` +
        `on conflict (caterer_id, date) do nothing;`
    );
  }
  lines.push("");
}

lines.push("commit;");
lines.push("");

const out = lines.join("\n");
writeFileSync(new URL("../supabase/seed.sql", import.meta.url), out);
console.log(
  `wrote supabase/seed.sql — ${caterers.length} caterers, ` +
    `${caterers.reduce((n, c) => n + c.packages.length, 0)} packages, ` +
    `${caterers.reduce((n, c) => n + c.menu.length, 0)} menu items, ` +
    `${addOns.length} add-ons`
);
